feat: Admin API 포토스팟/모임 관리 기능 구현
chalkak2023/Chalkak-Backend pull request #68
Opened 2023-03-04 08:16 UTC by boleesystem

### PR 타입
- [x] 기능 추가   

### 변경 사항
- 관리자 페이지 내 포토스팟 계정 관리 기능에 대한 API 구현
 1. 포토스팟 조회 기능
 2. 포토스팟 상세 조회 기능 _*추가 기능_
 3. 포토스팟 삭제(softDelete) 기능

- 관리자 페이지 내 모임 관리 기능에 대한 API 구현
 1. 모임 조회(검색, 페이지네이션 포함) 기능
 3. 모임 삭제(delete) 기능

### 테스트 결과
테스트 코드 작성 전

### 관련 이슈
- resolve #33   
- resolve #34  
- resolve #65
- resolve #35   
- resolve #36  

### 필요과제
- 테스트 코드 작성

2023-03-04 08:34 UTC, tstunas requested changes
수정 사항은 이 정도입니다.

2023-03-04 08:34 UTC, tstunas commented on src/admin/admin.service.ts
> +  async getAdminPhotospot(photospotId: number): Promise<Photospot | null> {
메소드 안에서 photospot이 _.isNil(photospot) 조건 검증을 거치면서 null인 경우는 사라집니다. 리턴 타입은 Promise<Photospot\>이 맞는 걸로 보입니다.

2023-03-04 08:34 UTC, tstunas commented on src/admin/admin.service.ts
> +    const page: number = (p as any) > 0 ? parseInt(p as any) : 1;
성훈님이 이미 리뷰했을 때 봤지만, p가 number으로 타입 정의되어있는데 굳이 type assertion을 쓰고, parseInt를 쓰실 필요가 있으셨을까요. 혹시 컨트롤러에서 p가 문자열로 받아져서 실제 실행 때 에러가 나서 그랬다면 컨트롤러의 @Query('p')에 ParseIntPipe를 쓰셔서 숫자로 변환시킬 필요가 있어보입니다.

2023-03-04 08:36 UTC, boleesystem commented on src/admin/admin.service.ts
> +  async getAdminPhotospot(photospotId: number): Promise<Photospot | null> {
수정 반영하겠습니다.

2023-03-04 08:36 UTC, boleesystem commented on src/admin/admin.service.ts
> +    const page: number = (p as any) > 0 ? parseInt(p as any) : 1;
리팩토링 단계에서 반영하겠습니다.

2023-03-04 08:48 UTC, tstunas requested changes

2023-03-04 08:48 UTC, tstunas commented on src/admin/admin.controller.ts
> +  async getAdminPhotospot(@Param('photospotId') photospotId: number): Promise<Photospot | null> {
여기의 null도 수정해야할 듯합니다.

2023-03-04 08:51 UTC, tstunas approved these changes

2023-03-04 08:52 UTC, merged

2023-03-14 22:01 UTC, boleesystem commented on src/admin/admin.controller.ts
> +  async getAdminPhotospot(@Param('photospotId') photospotId: number): Promise<Photospot | null> {
수정 반영하겠습니다. (수정 완료)