feat: meetups 모임 참여 동시성 문제 해결
chalkak2023/Chalkak-Backend pull request #99
Opened 2023-03-08 17:17 UTC by cchoseonghun

### PR 타입(하나 이상의 PR 타입을 선택)
- [x] 기능 추가   
- [x] 기능 수정   
- [ ] 기능 삭제   
- [ ] 버그 수정   
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 수정

### 변경 사항
- resolve #84 
  - Bull Queue와 Redis를 통해 대기열을 만들어 동시성 문제 해결
  - event-emitter를 통해 대기열에서 나와 처리된 응답 처리 제대로 안되는 문제 해결

### 테스트 결과
- meetups.service 두 메소드 제외하고 모두 정상

2023-03-08 23:33 UTC, tstunas requested changes
에러 응답은 잘 오는데, 201 응답이 안 옵니다.

2023-03-08 23:33 UTC, tstunas commented on src/meetups/meetups.service.ts
>    }
waitFinish는 Promise를 만들어서 반환합니다. 이미 프로미스를 반환하면서 비동기적으로 동작하는 함수이므로 async는 붙여주실 필요가 없습니다. await는 프로미스 앞에 붙어서 안에 있는 값을 꺼내는데 사용됩니다. 안의 함수가 값을 resolve하면 그 값을 반환하고, 에러를 reject하면 그 에러를 터뜨립니다.
이 경우에 resolve로 201 성공 응답 메시지를 반환하는데 그것을 요청한 사람에게 보내주는 return이 55번째 줄에 빠진 듯합니다. 일단 에러인 경우에는 await this.waitFininsh 안에서 throw exception이 되면서 exception filter가 알아서 응답을 보내주는데, 성공 메시지는 안 갑니다.
그러므로 55번째 줄에 return을 붙이고, 58번째 줄에서는 async를 빼는게 맞다고 생각합니다.

2023-03-08 23:33 UTC, tstunas commented on src/meetups/meetups.service.ts
>    }
한 번 Promise 반환을 빼고 async 함수로 해보려고도 했는데 setTimeout, listenFn 안에서 resolve 값을 어떻게 바깥으로 반환해야할지 감이 안 잡혀서 Promise 반환하는 식으로 만들게 되었습니다.

2023-03-09 00:01 UTC, cchoseonghun commented on src/meetups/meetups.service.ts
>    }
201 응답은 오지만 message를 같이 전달받지 못하네요. 
테스트 코드 작성하면서 함수가 Promise<unknown>을 반환하는걸로 되어있기에 
Promise<void>로 되게끔 바꾼게 문제였던 것 같습니다. 
해당 부분 수정하겠습니다.

2023-03-09 00:28 UTC, tstunas approved these changes
확인했습니다.

2023-03-09 00:29 UTC, merged